create table if not exists public.user_saved_schools (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  school_name text not null,
  category text not null check (category in ('Target', 'Reach', 'Safety')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, school_name)
);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists user_saved_schools_set_updated_at on public.user_saved_schools;

create trigger user_saved_schools_set_updated_at
before update on public.user_saved_schools
for each row
execute function public.set_updated_at();
