create table if not exists public.usnews_undergrad_rankings (
  id bigint generated by default as identity primary key,
  source_index integer unique,
  name text not null,
  location text,
  rank integer,
  description text,
  tuition text,
  in_state_tuition text,
  undergrad_enrollment text,
  sat_range text,
  acceptance_rate text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists usnews_undergrad_rankings_name_key on public.usnews_undergrad_rankings (name);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists usnews_undergrad_rankings_set_updated_at on public.usnews_undergrad_rankings;

create trigger usnews_undergrad_rankings_set_updated_at
before update on public.usnews_undergrad_rankings
for each row
execute function public.set_updated_at();
