create extension if not exists vector with schema extensions;

create table if not exists public.school_documents (
  id bigint generated by default as identity primary key,
  school_name text not null,
  source_type text not null default 'profile',
  title text not null,
  content text not null,
  metadata jsonb not null default '{}'::jsonb,
  embedding vector(1536),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists school_documents_school_name_idx
on public.school_documents (school_name);

create index if not exists school_documents_metadata_idx
on public.school_documents using gin (metadata);

create index if not exists school_documents_embedding_idx
on public.school_documents
using ivfflat (embedding vector_cosine_ops)
with (lists = 100);

create or replace function public.match_school_documents(
  query_embedding vector(1536),
  match_count int default 8,
  school_filter text default null
)
returns table (
  id bigint,
  school_name text,
  source_type text,
  title text,
  content text,
  metadata jsonb,
  similarity float
)
language sql
stable
as $$
  select
    school_documents.id,
    school_documents.school_name,
    school_documents.source_type,
    school_documents.title,
    school_documents.content,
    school_documents.metadata,
    1 - (school_documents.embedding <=> query_embedding) as similarity
  from public.school_documents
  where school_documents.embedding is not null
    and (school_filter is null or school_documents.school_name = school_filter)
  order by school_documents.embedding <=> query_embedding
  limit match_count;
$$;

alter table public.school_documents enable row level security;

drop policy if exists "authenticated users can read school documents" on public.school_documents;

create policy "authenticated users can read school documents"
on public.school_documents
for select
to authenticated
using (true);
